### PR TITLE
Add sharing/list_file_members endpoint

### PR DESCRIPTION
**Pull request by kayakyakr**
Almost exact copy of list_folder_members endpoint. Renamed a few files to make them less folder-specific.

### CODE REVIEW

**Comment by Jesus** [comment]
Hey, thanks for contributing to this gem!

There's a reason to have these names and it's because it's useful to maintain a direct mapping to the objects documented in the official Dropbox API.

I know we can reduce the amount of classes from this library with inheritance etc. However I don't think that's going to make it easier to maintain. I prefer to make Dropbox responsible for the design decisions and just have a plain wrapper to their API.

I can't merge this PR unless the previous naming is restored.

**Comment by jonfdaily** [comment]
@Jesus - do you think this will get merged into the gem?

**Comment by Jesus** [comment]
@kayakyakr do you have any plans to update this PR?

**Comment by kayakyakr** [comment]
@Jesus I already rewrote it to be compliant with the changes you requested. Don't know what else you wanted me to do. I'm otherwise swamped and am not working on the project that uses this gem, so don't have to make any major changes.

I made you and @jonfdaily collaborators on my fork, feel free to take the branch over and update it as you see fit.

**Comment by Jesus** [comment]
Ah sorry! I didn't notice your updates. Thank you!

I'll review and merge over the next few days.

**Pull request merged**
