### PR TITLE
Allow also any 1.x faraday dependency version.

### LINKED ISSUE #71: please use more reasonable faraday restriction, allow 1.0.1?
The gemspec currently says:

` spec.add_dependency "faraday", "<= 1.0"

https://github.com/Jesus/dropbox_api/blob/4c43dc78df3ab5ee95253580ce211ad2de4fe372/dropbox_api.gemspec#L26

That ends up meaning any faraday version less than or equal to 1.0.0, but no greater. 

This means 1.0.0 is allowed, but 1.0.1 released March 29 and [containing a few bugfixes](https://github.com/lostisland/faraday/compare/v1.0.0...v1.0.1) is *not* allowed by `dropbox_api`. An app using `dropbox_api` can use faraday 1.0.0, but not 1.0.1. 

I think this is probably not what you intended? Not sure what you intended? Perhaps `< 2.0`, meaning allow any 0.x and any 1.x? I would advocate that, I think?

Here is the commit where you changed gemspec to say `<= 1.0`, I'm afraid the commit message doesn't have much guidance. https://github.com/Jesus/dropbox_api/commit/71073700349cdfa14d8f31314c3ac7cf41c59ee3

### PR DESCRIPTION
**Pull request by simi**
closes #71

### CODE REVIEW

**Comment by jrochkind** [comment]
Why `<= 1.1`?  If Faraday uses semantic versioning, then it should be backwards compat up to 2.0, would it make more sense to say `> 2`, or `~> 1.0`?

**Comment by simi** [comment]
It is safe to move incrementally. Anyway I'm ok to change to `< 2`. @Jesus WDYT?

**Review by williamweckl — APPROVED** [review]

**Comment by simi** [comment]
@Jesus pingie

**Comment by jrochkind** [comment]
Hi, Faraday is up to 1.3.0 release, anyone using dropbox_api can still only use faraday 1.0.0 exactly. 

A merge and release would be really helpful! I am considering forking this to allow more recent faraday, but would really rather not!

**Comment by jrochkind** [comment]
However note that this PR still wouldn't allow faraday 1.3.0, it owuld only allow 1.1.x!

I think it really needs to allow < faraday 2, to keep this problem from happening again, since it has been demonstrated that it's difficult to get updates to dropbox_api to happen, let's fix it so we don't need to do this again in a month!

**Comment by simi** [comment]
@jrochkind I have updated the PR.

@Jesus any plan on merge release? Anything I can help with?

**Comment by Jesus** [comment]
Oops I haven't seen those notifications until now, sorry!

**Comment by simi** [comment]
@Jesus thanks! Any plans for release?

**Pull request merged**
