### PR TITLE
remove version lock

### PR DESCRIPTION
**Pull request by seuros**
can you release a new version please ?

### CODE REVIEW

**Comment by Jesus** [comment]
Why is the restriction `<= 1.0` a problem?

**Comment by seuros** [comment]
Because Faraday 1.0 is out, and i cannot use this gem natively without having it downgrade faraday in my stack.

**Comment by Jesus** [comment]
I would expect this to work with Faraday 1.0 since it's set to `<= 1.0` (notice the less **or equal**).

**Comment by seuros** [comment]
I dont recall exactly, i think i tried to add it in a stack with an older version of faraday then. 
I will close this PR. Thanks.

**Pull request closed without merging**
