### PR TITLE
Feature/search continue

### PR DESCRIPTION
**Pull request by wakarana1**
This implements search_continue

### CODE REVIEW

**Comment by artinboghosian** [comment]
@Jesus. Any idea when this will get merged in? Thanks for all your hard work on this API integration, very straightforward and easy to understand code 👍

**Comment by artinboghosian** [comment]
@artinboghosian upping this. Hope we can get it merged soon if all is good.

**Comment by artinboghosian** [comment]
@Jesus upping this again

**Comment by Jesus** [comment]
Sorry for the long wait!

You can expect a release in a few days.

**Comment by artinboghosian** [comment]
@Jesus thank you so much

**Pull request merged**
